
matrix:
 include:
  - os: linux
    dist: bionic
    python: "2.7"
  - os: linux
    dist: bionic
    python: "3.7"
# Does not support docker in osx
#  - os: osx
#   osx_image: xcode10.2
#    language: generic 

# Broken as per: https://github.com/travis-ci/travis-ci/issues/9929#issuecomment-410710458
#  - os: osx
#   osx_image: xcode10.2
#    python: "3.6-dev"

# Merging parallel build results https://docs.coveralls.io/parallel-build-webhook
env: 
 - COVERALLS_PARALLEL=true

notifications:
 webhooks: https://coveralls.io/webhook

language: python

services:
 - docker

before_install:
 # Ensures we have a recent python3 
 # https://docs.python-guide.org/starting/install3/osx/
 #- if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install python ; fi
 # Currently there is an issue with 1.16 and SCS; this installs a custom version
 # https://stackoverflow.com/a/48185032
 - pip install -U --only-binary=numpy, scipy numpy==1.15.4 
 - pip install -U pybind11>=2.3
# dask.distributed dropped support for python2 so we need to install the last compatabile version
 - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]] ; then pip install -U distributed==1.28.1 ; fi 

install:
 - pip install pytest
 - pip install pytest-cov
 - pip install coveralls
 - python setup.py install 

script:
 - pip freeze --local 
# Pre-pull docker images
 - docker pull jeffreyhokanson/oas:v1
 - docker pull jeffreyhokanson/multif:v25
 - docker pull jeffreyhokanson/naca0012
 - pytest --cov=psdr --cov-branch --cov-config=.coveragerc tests/

after_success:
 - coveralls

