dist: xenial

language: python

python: 
 - "2.7"
# - "3.7"


# https://stackoverflow.com/a/48185032
before_install:
# Currently there is an issue with 1.16 and SCS
 - pip install -U --only-binary=numpy, scipy numpy==1.16.2

install:
 - pip install pytest
 - pip install pytest-cov
 - pip install coveralls
 - python setup.py install 

script:
 - pip freeze --local 
 - pytest --cov=psdr tests/

after_success:
 - coveralls


