language: python

python: 
 - "2.7"

install:
 - pip install pytest
 - pip install pytest-cov
 - pip install coveralls
 - python setup.py install 

script:
 - pip freeze --local 
 - pytest --cov=mor tests/
after_success:
 - coveralls

