
matrix:
 include:
  - os: linux
    dist: xenial
    python: "2.7"
  - os: linux
    dist: xenial
    python: "3.7"
  - os: osx
    osx_image: xcode10.2
    python: "3.6-dev"

language: python

services:
 - docker

before_install:
 # Currently there is an issue with 1.16 and SCS; this installs a custom version
 # https://stackoverflow.com/a/48185032
 - pip install -U --only-binary=numpy, scipy numpy==1.15.4
 - docker pull jeffreyhokanson/oas:v1
 - docker pull jeffreyhokanson/multif:v25

install:
 - pip install pytest
 - pip install pytest-cov
 - pip install coveralls
 - python setup.py install 

script:
 - pip freeze --local 
 - pytest --cov=psdr tests/

after_success:
 - if python --version | grep -c "3.7" ; then coveralls ; fi


