
matrix:
 include:
#  - os: linux
#    dist: bionic
#    python: "2.7"
  - os: linux
    dist: bionic
    python: "3.7"
#  - os: linux
#    dist: bionic
#    python: "3.8"
# Does not support docker in osx
#  - os: osx
#   osx_image: xcode10.2
#    language: generic 

# Broken as per: https://github.com/travis-ci/travis-ci/issues/9929#issuecomment-410710458
#  - os: osx
#   osx_image: xcode10.2
#    python: "3.6-dev"

# Merging parallel build results https://docs.coveralls.io/parallel-build-webhook
env: 
 - COVERALLS_PARALLEL=true

notifications:
 webhooks: https://coveralls.io/webhook

language: python

services:
 - docker

before_install:
# - pip3 install -U --only-binary=numpy --only-binary=scipy numpy==1.15.4 scipy scs osqp cvxopt cvxpy
 - pip3 install -U --only-binary=numpy --only-binary=scipy numpy scipy scs osqp cvxopt cvxpy


install:
 - pip3 install -U pytest pytest-cov coveralls
 - python3 setup.py install 

script:
 - pip3 freeze --local 
# Pre-pull docker images
 - docker pull jeffreyhokanson/oas:v1
 - docker pull jeffreyhokanson/multif:v25
 - docker pull jeffreyhokanson/naca0012
 - pytest --cov=psdr --cov-branch --cov-config=.coveragerc tests/

after_success:
 - coveralls

notifications:
  webhooks: https://coveralls.io/webhook
